version: '3.8'
services:
  db:
    build: .
    restart: always
    environment:
      - POSTGRES_DB=rstdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Food4fi
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - type: bind
        source: /mnt/c/Users/emanuel/projects/jpe/rst-database
        target: /opt/data
volumes:
  db:
