/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('trap_locations').del()
  await knex('trap_locations').insert([
    {
      trapName: 'Mill Creek RST',
      programId: 1,
      dataRecorderId: 1,
      dataRecorderAgencyId: 2,
      siteName: 'Mill Creek RST',
      coneSizeFt: 5,
      xCoord: '40.05474',
      yCoord: '-122.029',
      gageNumber: 11381500,
      gageAgency: 9,
    },
    {
      trapName: 'Deer Creek RST',
      programId: 2,
      dataRecorderId: 1,
      dataRecorderAgencyId: 2,
      siteName: 'Deer Creek RST',
      coneSizeFt: 5,
      xCoord: '40.01097',
      yCoord: '-121.961',
      gageNumber: 11383500,
      gageAgency: 9,
    },
    {
      trapName: 'Steep Riffle RST',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Steep Riffle',
      coneSizeFt: 8,
      xCoord: 39.4621,
      yCoord: -121.604633,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Steep Side Channel',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Steep Riffle',
      coneSizeFt: 8,
      xCoord: 39.462014,
      yCoord: -121.604028,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: "Steep Riffle 10'' ext",
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Steep Riffle',
      coneSizeFt: 8,
      xCoord: 39.4621,
      yCoord: -121.604633,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Eye riffle north',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Eye Riffle',
      coneSizeFt: 8,
      xCoord: 39.456597,
      yCoord: -121.615317,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Eye riffle Side Channel',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Eye Riffle',
      coneSizeFt: 8,
      xCoord: 39.456233,
      yCoord: -121.614508,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Live Oak',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Live Oak',
      coneSizeFt: 8,
      xCoord: 39.270811,
      yCoord: -121.632636,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Herringer east',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Herringer Riffle',
      coneSizeFt: 8,
      xCoord: 39.315156,
      yCoord: -121.625519,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Herringer west',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Herringer Riffle',
      coneSizeFt: 8,
      xCoord: 39.315156,
      yCoord: -121.625519,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Herringer Upper west',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Herringer Riffle',
      coneSizeFt: 8,
      xCoord: 39.315156,
      yCoord: -121.625519,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Sunset East Bank',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Sunset Pumps',
      coneSizeFt: 8,
      xCoord: 39.245658,
      yCoord: -121.636425,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Sunset West Bank',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Sunset Pumps',
      coneSizeFt: 8,
      xCoord: 39.245658,
      yCoord: -121.636425,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Shawns East',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Shawns Beach',
      coneSizeFt: 8,
      xCoord: 39.21215,
      yCoord: -121.615411,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Shawns West',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Shawns Beach',
      coneSizeFt: 8,
      xCoord: 39.21215,
      yCoord: -121.615411,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Gateway main1',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Gateway Riffle',
      coneSizeFt: 8,
      xCoord: 39.457069,
      yCoord: -121.625161,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Gateway Rootball',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Gateway Riffle',
      coneSizeFt: 8,
      xCoord: 39.457069,
      yCoord: -121.625161,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: "Gateway Main 400' Up River",
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Gateway Riffle',
      coneSizeFt: 8,
      xCoord: 39.457069,
      yCoord: -121.625161,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Gateway Rootball River Left',
      programId: 3,
      dataRecorderId: 9,
      dataRecorderAgencyId: 3,
      siteName: 'Gateway Riffle',
      coneSizeFt: 8,
      xCoord: 39.457069,
      yCoord: -121.625161,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Hallwood 1',
      programId: 4,
      dataRecorderId: 10,
      dataRecorderAgencyId: 3,
      siteName: 'Hallwood',
      coneSizeFt: 8,
      xCoord: 39.182161,
      yCoord: -121.506503,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'Hallwood 2',
      programId: 4,
      dataRecorderId: 10,
      dataRecorderAgencyId: 3,
      siteName: 'Hallwood',
      coneSizeFt: 8,
      xCoord: 39.182161,
      yCoord: -121.506503,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'FlowWest test 1',
      programId: 5,
      dataRecorderId: 11,
      dataRecorderAgencyId: null,
      siteName: 'FlowWest Test',
      coneSizeFt: null,
      xCoord: null,
      yCoord: null,
      gageNumber: null,
      gageAgency: null,
    },
    {
      trapName: 'FlowWest test 2',
      programId: 5,
      dataRecorderId: 11,
      dataRecorderAgencyId: null,
      siteName: 'FlowWest Test',
      coneSizeFt: null,
      xCoord: null,
      yCoord: null,
      gageNumber: null,
      gageAgency: null,
    },
  ])
}
